# Colors ({{ displayName }})

# Default colors
[colors.primary]
background = '{{ accent12 }}'
foreground = '{{ accent7 }}'

# Normal colors
[colors.normal]
black   = '{{ accent21 }}'
red     = '{{ ansiRed }}'
green   = '{{ ansiGreen }}'
yellow  = '{{ ansiYellow }}'
blue    = '{{ ansiBlue }}'
magenta = '{{ ansiMagenta }}'
cyan    = '{{ ansiCyan }}'
white   = '{{ ansiWhite }}'

# Bright colors
[colors.bright]
black   = '{{ ansiBrightBlack }}'
red     = '{{ ansiBrightRed }}'
green   = '{{ ansiBrightGreen }}'
yellow  = '{{ ansiBrightYellow }}'
blue    = '{{ ansiBrightBlue }}'
magenta = '{{ ansiBrightMagenta }}'
cyan    = '{{ ansiBrightCyan }}'
white   = '{{ ansiBrightWhite }}'

[colors.selection]
text       = 'CellForeground'
background = '{{ accent38 }}'

[colors.cursor]
cursor = '{{ accent1 }}'
