# Aura 2026 Soft Dark (Soft Text)

background = #0D0B13
foreground = #c1c0c3
cursor-color = #C4B5FD
selection-background = #6F4FD8
selection-foreground = #c1c0c3

palette = 0=#0A090F
palette = 1=#F87171
palette = 2=#34D399
palette = 3=#F6B86A
palette = 4=#A277FF
palette = 5=#61FFCA
palette = 6=#A277FF
palette = 7=#DDD9E7
palette = 8=#6D6D6D
palette = 9=#FCA5A5
palette = 10=#61FFCA
palette = 11=#FFCA85
palette = 12=#C4B5FD
palette = 13=#9FFFE2
palette = 14=#C4B5FD
palette = 15=#F2F0F5
