import {
  AuraBasePalette,
  AuraSemanticPalette,
  AuraVariantFamily,
} from '../roles/types'

// Hand-tuned daylight companions to Aura's existing hues. These are source
// colors, not an inversion of the dark theme or colors sampled from a port.
export const auraLightColors = {
  paper: '#FCFBFE',
  white: '#FFFFFF',
  chrome: '#F4F2F7',
  surface: '#F1EEF5',
  line: '#F5F3F8',
  hover: '#E8E3EF',
  tabs: '#ECE8F1',
  border: '#E2DCE9',
  borderStrong: '#C7BED3',
  ink: '#342C42',
  inkStrong: '#241B30',
  inkMuted: '#60576D',
  inkSubtle: '#746A80',
  disabled: '#A398AE',
  comment: '#6D6377',
  purple: '#7043C1',
  purpleStrong: '#5F35AB',
  purpleSoft: '#8659CF',
  selection: '#E7DFF5',
  mint: '#007A58',
  mintStrong: '#006B4D',
  mintSoft: '#2F8869',
  lime: '#43751E',
  blue: '#066B88',
  teal: '#097567',
  lavender: '#8541B2',
  lavenderStrong: '#7934A8',
  lavenderMuted: '#706184',
  pink: '#A23098',
  pinkSoft: '#914587',
  red: '#B93844',
  redStrong: '#AD303E',
  amber: '#90620F',
  amberStrong: '#80540A',
  orange: '#9A5B15',
  orangeStrong: '#874C0E',
  debug: '#F3DEB7',
  breakpoint: '#F7ECD8',
}

export const auraLightBase2026: AuraBasePalette = {
  shadow: '#241B3018',
  background: auraLightColors.paper,
  appBackground: auraLightColors.chrome,
  sidebar: auraLightColors.chrome,
  panel: auraLightColors.chrome,
  surface: auraLightColors.surface,
  surfaceAlt: auraLightColors.line,
  surfaceHover: auraLightColors.hover,
  elevated: auraLightColors.white,
  border: auraLightColors.border,
  borderStrong: auraLightColors.borderStrong,
  foreground: auraLightColors.ink,
  foregroundStrong: auraLightColors.inkStrong,
  foregroundMuted: auraLightColors.inkMuted,
  foregroundSubtle: auraLightColors.inkSubtle,
  disabled: auraLightColors.disabled,
  comment: auraLightColors.comment,
  transparent: '#00000000',
}

export const auraLightSemantic2026: AuraSemanticPalette = {
  brand: {
    mint: auraLightColors.mint,
    lime: auraLightColors.lime,
    blue: auraLightColors.blue,
    teal: auraLightColors.teal,
    lavender: auraLightColors.lavender,
    lavenderBright: auraLightColors.lavenderStrong,
    lavenderMuted: auraLightColors.lavenderMuted,
    pink: auraLightColors.pink,
    pinkSoft: auraLightColors.pinkSoft,
  },
  status: {
    error: auraLightColors.red,
    errorBright: auraLightColors.redStrong,
    success: auraLightColors.mint,
    successBright: auraLightColors.lime,
    warning: auraLightColors.amber,
    warningBright: auraLightColors.amberStrong,
    orange: auraLightColors.orange,
    orangeBright: auraLightColors.orangeStrong,
    info: auraLightColors.teal,
    infoBright: auraLightColors.blue,
  },
}

export const auraLightFamily: AuraVariantFamily = {
  name: 'Aura Light 2026',
  slug: 'aura-light-2026',
  accent: auraLightColors.purple,
  accentBright: auraLightColors.purpleStrong,
  accentSoft: auraLightColors.purpleSoft,
  companion: auraLightColors.mint,
  companionBright: auraLightColors.mintStrong,
  companionSoft: auraLightColors.mintSoft,
}
