import {
  AuraBasePalette,
  AuraSemanticPalette,
  AuraVariantFamily,
} from '../roles/types'
import { auraMint } from './aura'

// Hand-tuned daylight companions to Aura's existing hues. These are source
// colors, not an inversion of the dark theme or colors sampled from a port.
export const auraLightColors = {
  paper: '#F8F9FA',
  white: '#FFFFFF',
  chrome: '#F0F2F5',
  surface: '#EEF1F4',
  line: '#F2F4F6',
  hover: '#E5E9EF',
  tabs: '#E7EBF0',
  border: '#DCE1E7',
  borderStrong: '#BFC7D2',
  ink: '#30323C',
  inkStrong: '#22242E',
  inkMuted: '#59616F',
  inkSubtle: '#687381',
  disabled: '#A0A8B4',
  comment: '#606C78',
  purple: '#7043C1',
  purpleStrong: '#5F35AB',
  purpleSoft: '#8659CF',
  selection: '#E9E5F3',
  mint: auraMint,
  mintText: '#007A58',
  mintHover: '#48E8B5',
  mintOutline: '#148765',
  onMint: '#123B2D',
  inverse: '#282431',
  inverseHover: '#373042',
  mintStrong: '#006B4D',
  mintSoft: '#2F8869',
  lime: '#43751E',
  blue: '#066B88',
  teal: '#097567',
  lavender: '#8541B2',
  lavenderStrong: '#7934A8',
  lavenderMuted: '#706184',
  pink: '#A23098',
  pinkSoft: '#914587',
  red: '#B93844',
  redStrong: '#AD303E',
  amber: '#90620F',
  amberStrong: '#80540A',
  orange: '#9A5B15',
  orangeStrong: '#874C0E',
  debug: '#F3DEB7',
  breakpoint: '#F7ECD8',
}

export const auraLightBase2026: AuraBasePalette = {
  shadow: '#20263214',
  background: auraLightColors.paper,
  appBackground: auraLightColors.chrome,
  sidebar: auraLightColors.chrome,
  panel: auraLightColors.chrome,
  surface: auraLightColors.surface,
  surfaceAlt: auraLightColors.line,
  surfaceHover: auraLightColors.hover,
  elevated: auraLightColors.white,
  border: auraLightColors.border,
  borderStrong: auraLightColors.borderStrong,
  foreground: auraLightColors.ink,
  foregroundStrong: auraLightColors.inkStrong,
  foregroundMuted: auraLightColors.inkMuted,
  foregroundSubtle: auraLightColors.inkSubtle,
  disabled: auraLightColors.disabled,
  comment: auraLightColors.comment,
  transparent: '#00000000',
}

export const auraLightSemantic2026: AuraSemanticPalette = {
  brand: {
    mint: auraLightColors.mint,
    mintText: auraLightColors.mintText,
    mintHover: auraLightColors.mintHover,
    onMint: auraLightColors.onMint,
    lime: auraLightColors.lime,
    blue: auraLightColors.blue,
    teal: auraLightColors.teal,
    lavender: auraLightColors.lavender,
    lavenderBright: auraLightColors.lavenderStrong,
    lavenderMuted: auraLightColors.lavenderMuted,
    pink: auraLightColors.pink,
    pinkSoft: auraLightColors.pinkSoft,
  },
  status: {
    error: auraLightColors.red,
    errorBright: auraLightColors.redStrong,
    success: auraLightColors.mintText,
    successBright: auraLightColors.lime,
    warning: auraLightColors.amber,
    warningBright: auraLightColors.amberStrong,
    orange: auraLightColors.orange,
    orangeBright: auraLightColors.orangeStrong,
    info: auraLightColors.teal,
    infoBright: auraLightColors.blue,
  },
}

export const auraLightFamily: AuraVariantFamily = {
  name: 'Aura Light 2026',
  slug: 'aura-light-2026',
  accent: auraLightColors.purple,
  accentBright: auraLightColors.purpleStrong,
  accentSoft: auraLightColors.purpleSoft,
  companion: auraLightColors.mintText,
  companionBright: auraLightColors.mintStrong,
  companionSoft: auraLightColors.mintSoft,
}
