import { AuraPalette, AuraVariantFamily, LegacyAuraScheme } from './types'
import { auraInkBase2026 } from './base'
import { auraVariantFamilies } from './variants'
import { createAuraPalette } from './create-aura-palette'

export function compileLegacyScheme(palette: AuraPalette): LegacyAuraScheme {
  const { base, semantic, ui, syntax, ansi } = palette

  return {
    accent0: base.shadow,
    accent1: ui.accentBright,
    accent2: syntax.string,
    accent3: syntax.function,
    accent4: semantic.greenBright,
    accent5: semantic.red,
    accent6: syntax.property,
    accent7: base.foregroundStrong,
    accent8: syntax.comment,
    accent9: base.foreground,
    accent10: base.foregroundMuted,
    accent11: base.shadow,
    accent12: base.background,
    accent13: base.disabled,
    accent14: `${ui.accentBright}7F`,
    accent15: base.disabled,
    accent16: base.transparent,
    accent17: `${base.foregroundSubtle}33`,
    accent18: `${base.foregroundSubtle}00`,
    accent19: `${semantic.green}7F`,
    accent20: ui.selection,
    accent21: base.sidebar,
    accent22: base.foregroundSubtle,
    accent23: base.border,
    accent24: base.appBackground,
    accent25: ui.linkHover,
    accent26: `${semantic.green}23`,
    accent27: `${semantic.red}20`,
    accent28: base.appBackground,
    accent29: base.shadow,
    accent30: base.surface,
    accent31: semantic.orange,
    accent32: syntax.type,
    accent33: base.surfaceAlt,
    accent34: base.transparent,
    accent35: base.disabled,
    accent36: ui.debugBackground,
    accent37: ui.breakpointBackground,
    accent38: ui.selectionSolid,
    accent39: base.surface,
    accent40: ui.focusBorder,
    accent41: ui.successSurface,
    accent42: ui.warningSurface,
    accent43: ui.errorSurface,
    accent44: ui.infoSurface,
    accent45: ui.subtleAccentSurface,
    accent46: ui.mediumAccentSurface,
    accent47: ui.strongAccentSurface,
    accent48: base.elevated,
    accent49: base.surface,
    accent50: ui.foregroundOverlayLow,
    accent51: ui.foregroundOverlayHigh,
    accent52: ui.scrollbar,
    accent53: ui.scrollbarHover,
    accent54: ui.scrollbarActive,
    accent55: base.elevated,
    accent56: base.surfaceAlt,
    accent57: syntax.namespace,
    accent58: base.foregroundSubtle,
    accent59: syntax.variable,
    accent60: syntax.parameter,
    accent61: syntax.label,

    ansiBlack: ansi.black,
    ansiRed: ansi.red,
    ansiGreen: ansi.green,
    ansiYellow: ansi.yellow,
    ansiBlue: ansi.blue,
    ansiMagenta: ansi.magenta,
    ansiCyan: ansi.cyan,
    ansiWhite: ansi.white,
    ansiBrightBlack: ansi.brightBlack,
    ansiBrightRed: ansi.brightRed,
    ansiBrightGreen: ansi.brightGreen,
    ansiBrightYellow: ansi.brightYellow,
    ansiBrightBlue: ansi.brightBlue,
    ansiBrightMagenta: ansi.brightMagenta,
    ansiBrightCyan: ansi.brightCyan,
    ansiBrightWhite: ansi.brightWhite,
    ansiDimBlack: ansi.dimBlack,
    ansiDimRed: ansi.dimRed,
    ansiDimGreen: ansi.dimGreen,
    ansiDimYellow: ansi.dimYellow,
    ansiDimBlue: ansi.dimBlue,
    ansiDimMagenta: ansi.dimMagenta,
    ansiDimCyan: ansi.dimCyan,
    ansiDimWhite: ansi.dimWhite,

    syntaxAttribute: syntax.attribute,
    syntaxBoolean: syntax.boolean,
    syntaxClass: syntax.class,
    syntaxComment: syntax.comment,
    syntaxCommentDoc: syntax.commentDoc,
    syntaxConstant: syntax.constant,
    syntaxConstructor: syntax.constructor,
    syntaxDecorator: syntax.decorator,
    syntaxEmbedded: syntax.embedded,
    syntaxEnum: syntax.enum,
    syntaxEnumMember: syntax.enumMember,
    syntaxFunction: syntax.function,
    syntaxFunctionSpecial: syntax.functionSpecial,
    syntaxKeyword: syntax.keyword,
    syntaxLabel: syntax.label,
    syntaxLink: syntax.link,
    syntaxMacro: syntax.macro,
    syntaxNamespace: syntax.namespace,
    syntaxNumber: syntax.number,
    syntaxOperator: syntax.operator,
    syntaxParameter: syntax.parameter,
    syntaxProperty: syntax.property,
    syntaxPunctuation: syntax.punctuation,
    syntaxPunctuationMuted: syntax.punctuationMuted,
    syntaxRegexp: syntax.regexp,
    syntaxSelector: syntax.selector,
    syntaxString: syntax.string,
    syntaxStringEscape: syntax.stringEscape,
    syntaxStringSpecial: syntax.stringSpecial,
    syntaxTag: syntax.tag,
    syntaxTitle: syntax.title,
    syntaxType: syntax.type,
    syntaxVariable: syntax.variable,
    syntaxVariableSpecial: syntax.variableSpecial,

    uiAccent: ui.accent,
    uiAccentBright: ui.accentBright,
    uiAccentSoft: ui.accentSoft,
    uiCompanion: ui.companion,
    uiCompanionBright: ui.companionBright,
    uiCompanionSoft: ui.companionSoft,
    uiSelection: ui.selection,
    uiSelectionSoft: ui.selectionSoft,
    uiSelectionStrong: ui.selectionStrong,
    uiLineHighlight: ui.lineHighlight,
    uiLink: ui.link,
    uiLinkHover: ui.linkHover,
    uiButton: ui.button,
    uiButtonHover: ui.buttonHover,

    paletteName: palette.name,
    paletteSlug: palette.slug,
  }
}

export function createLegacySchemeFromFamily(
  family: AuraVariantFamily
): LegacyAuraScheme {
  return compileLegacyScheme(createAuraPalette(family))
}

export const variantSchemes = auraVariantFamilies.map((family) => ({
  family,
  scheme: createLegacySchemeFromFamily(family),
}))

export const inkVariantScheme = {
  family: {
    ...auraVariantFamilies[0],
    name: 'Aura Ink 2026',
    slug: 'aura-ink-2026',
  },
  scheme: compileLegacyScheme(
    createAuraPalette(
      {
        ...auraVariantFamilies[0],
        name: 'Aura Ink 2026',
        slug: 'aura-ink-2026',
      },
      auraInkBase2026
    )
  ),
}
