import { AuraPalette, AuraVariantFamily, LegacyAuraScheme } from './types'
import { auraDefaultFamily, auraInkBase2026 } from './base'
import { auraVariantFamilies } from './variants'
import { createAuraPalette } from './create-aura-palette'

export function compileLegacyScheme(palette: AuraPalette): LegacyAuraScheme {
  const { base, semantic, ui, syntax, ansi } = palette
  const { brand, status } = semantic

  return {
    accent0: base.shadow,
    accent1: ui.accentBright,
    accent2: syntax.string,
    accent3: syntax.function,
    accent4: brand.mint,
    accent5: status.error,
    accent6: syntax.property,
    accent7: base.foregroundStrong,
    accent8: syntax.comment,
    accent9: base.foreground,
    accent10: base.foregroundMuted,
    accent11: base.shadow,
    accent12: base.background,
    accent13: base.disabled,
    accent14: `${ui.accentBright}7F`,
    accent15: base.disabled,
    accent16: base.transparent,
    accent17: `${base.foregroundSubtle}33`,
    accent18: `${base.foregroundSubtle}00`,
    accent19: `${status.success}7F`,
    accent20: ui.selection,
    accent21: base.sidebar,
    accent22: base.foregroundSubtle,
    accent23: base.border,
    accent24: base.appBackground,
    accent25: ui.linkHover,
    accent26: `${status.success}23`,
    accent27: `${status.error}20`,
    accent28: base.appBackground,
    accent29: base.shadow,
    accent30: base.surface,
    accent31: status.orange,
    accent32: syntax.type,
    accent33: base.surfaceAlt,
    accent34: base.transparent,
    accent35: base.disabled,
    accent36: ui.debugBackground,
    accent37: ui.breakpointBackground,
    accent38: ui.selectionSolid,
    accent39: base.surface,
    accent40: ui.focusBorder,
    accent41: ui.successSurface,
    accent42: ui.warningSurface,
    accent43: ui.errorSurface,
    accent44: ui.infoSurface,
    accent45: ui.subtleAccentSurface,
    accent46: ui.mediumAccentSurface,
    accent47: ui.strongAccentSurface,
    accent48: base.elevated,
    accent49: base.surface,
    accent50: ui.foregroundOverlayLow,
    accent51: ui.foregroundOverlayHigh,
    accent52: ui.scrollbar,
    accent53: ui.scrollbarHover,
    accent54: ui.scrollbarActive,
    accent55: base.elevated,
    accent56: base.surfaceHover,
    accent57: syntax.namespace,
    accent58: base.foregroundSubtle,
    accent59: syntax.variable,
    accent60: syntax.parameter,
    accent61: syntax.label,

    ansiBlack: ansi.black,
    ansiRed: ansi.red,
    ansiGreen: ansi.green,
    ansiYellow: ansi.yellow,
    ansiBlue: ansi.blue,
    ansiMagenta: ansi.magenta,
    ansiCyan: ansi.cyan,
    ansiWhite: ansi.white,
    ansiBrightBlack: ansi.brightBlack,
    ansiBrightRed: ansi.brightRed,
    ansiBrightGreen: ansi.brightGreen,
    ansiBrightYellow: ansi.brightYellow,
    ansiBrightBlue: ansi.brightBlue,
    ansiBrightMagenta: ansi.brightMagenta,
    ansiBrightCyan: ansi.brightCyan,
    ansiBrightWhite: ansi.brightWhite,
    ansiDimBlack: ansi.dimBlack,
    ansiDimRed: ansi.dimRed,
    ansiDimGreen: ansi.dimGreen,
    ansiDimYellow: ansi.dimYellow,
    ansiDimBlue: ansi.dimBlue,
    ansiDimMagenta: ansi.dimMagenta,
    ansiDimCyan: ansi.dimCyan,
    ansiDimWhite: ansi.dimWhite,

    syntaxAttribute: syntax.attribute,
    syntaxBoolean: syntax.boolean,
    syntaxClass: syntax.class,
    syntaxComment: syntax.comment,
    syntaxCommentDoc: syntax.commentDoc,
    syntaxConstant: syntax.constant,
    syntaxConstructor: syntax.constructor,
    syntaxDecorator: syntax.decorator,
    syntaxEmbedded: syntax.embedded,
    syntaxEnum: syntax.enum,
    syntaxEnumMember: syntax.enumMember,
    syntaxFunction: syntax.function,
    syntaxFunctionSpecial: syntax.functionSpecial,
    syntaxKeyword: syntax.keyword,
    syntaxLabel: syntax.label,
    syntaxLink: syntax.link,
    syntaxMacro: syntax.macro,
    syntaxNamespace: syntax.namespace,
    syntaxNumber: syntax.number,
    syntaxOperator: syntax.operator,
    syntaxParameter: syntax.parameter,
    syntaxProperty: syntax.property,
    syntaxPunctuation: syntax.punctuation,
    syntaxPunctuationMuted: syntax.punctuationMuted,
    syntaxRegexp: syntax.regexp,
    syntaxSelector: syntax.selector,
    syntaxString: syntax.string,
    syntaxStringEscape: syntax.stringEscape,
    syntaxStringSpecial: syntax.stringSpecial,
    syntaxTag: syntax.tag,
    syntaxTitle: syntax.title,
    syntaxType: syntax.type,
    syntaxVariable: syntax.variable,
    syntaxVariableSpecial: syntax.variableSpecial,

    uiAccent: ui.accent,
    uiAccentBright: ui.accentBright,
    uiAccentSoft: ui.accentSoft,
    uiCompanion: ui.companion,
    uiCompanionBright: ui.companionBright,
    uiCompanionSoft: ui.companionSoft,
    uiHighlight: ui.highlight.base,
    uiHighlightBright: ui.highlight.bright,
    uiHighlightHover: ui.highlight.hover,
    uiHighlightForeground: ui.highlight.foreground,
    uiSelection: ui.selection,
    uiSelectionSoft: ui.selectionSoft,
    uiSelectionStrong: ui.selectionStrong,
    uiSelectionSolid: ui.selectionSolid,
    uiListSelection: ui.listSelection,
    uiListSelectionFocus: ui.listSelectionFocus,
    uiWarning: ui.warning,
    uiModified: ui.modified,
    uiActionHover: ui.actionHover,
    uiLineHighlight: ui.lineHighlight,
    uiLink: ui.link,
    uiLinkHover: ui.linkHover,
    uiButton: ui.button,
    uiButtonHover: ui.buttonHover,
    uiActionBackground: ui.action.background,
    uiActionForeground: ui.action.foreground,
    uiActionHoverBackground: ui.action.hoverBackground,
    uiActionHoverForeground: ui.action.hoverForeground,
    uiActionSecondaryHoverBackground: ui.action.secondaryHoverBackground,
    uiLinkForeground: ui.linkRole.foreground,
    uiLinkHoverForeground: ui.linkRole.hoverForeground,
    uiRemoteBackground: ui.remote.background,
    uiRemoteForeground: ui.remote.foreground,
    uiRemoteHoverBackground: ui.remote.hoverBackground,
    uiRemoteHoverForeground: ui.remote.hoverForeground,
    uiEditorSelection: ui.selectionRole.editor,
    uiEditorSelectionInactive: ui.selectionRole.editorInactive,
    uiEditorSelectionStrong: ui.selectionRole.editorStrong,
    uiListSelectionBackground: ui.selectionRole.list,
    uiListSelectionFocusBackground: ui.selectionRole.listFocus,
    uiSelectionSolidBackground: ui.selectionRole.solid,
    uiStatusModified: ui.status.modified,
    uiStatusSuccessSurface: ui.status.successSurface,
    uiStatusWarning: ui.status.warning,
    uiStatusWarningSurface: ui.status.warningSurface,
    uiStatusErrorSurface: ui.status.errorSurface,
    uiStatusInfoSurface: ui.status.infoSurface,
    uiSurfaceElevated: ui.surfaceRole.elevated,
    uiSurfacePanel: ui.surfaceRole.panel,
    uiSurfaceHover: ui.surfaceRole.hover,
    uiSurfaceHoverOverlay: ui.surfaceRole.hoverOverlay,
    uiSurfaceStrongOverlay: ui.surfaceRole.strongOverlay,
    uiSurfaceTile: ui.surfaceRole.tile,
    uiSurfaceTileHover: ui.surfaceRole.tileHover,
    uiWelcomeBackground: ui.welcome.background,
    uiWelcomeTileBackground: ui.welcome.tileBackground,
    uiWelcomeTileHoverBackground: ui.welcome.tileHoverBackground,
    uiWelcomeTileBorder: ui.welcome.tileBorder,
    uiWelcomeStepTitleForeground: ui.welcome.stepTitleForeground,

    paletteName: palette.name,
    paletteSlug: palette.slug,
  }
}

export function createLegacySchemeFromFamily(
  family: AuraVariantFamily
): LegacyAuraScheme {
  return compileLegacyScheme(createAuraPalette(family))
}

export const variantSchemes = auraVariantFamilies.map((family) => ({
  family,
  scheme: createLegacySchemeFromFamily(family),
}))

export const inkVariantScheme = {
  family: {
    ...auraDefaultFamily,
    name: 'Aura Ink 2026',
    slug: 'aura-ink-2026',
  },
  scheme: compileLegacyScheme(
    createAuraPalette(
      {
        ...auraDefaultFamily,
        name: 'Aura Ink 2026',
        slug: 'aura-ink-2026',
      },
      auraInkBase2026
    )
  ),
}
