import { auraBase2026, auraSemantic2026 } from './base'
import { AuraBasePalette, AuraPalette, AuraVariantFamily } from './types'
import { withAlpha } from './utils'

export function createAuraPalette(
  family: AuraVariantFamily,
  baseOverride?: AuraBasePalette
): AuraPalette {
  const base = baseOverride ?? auraBase2026
  const semantic = auraSemantic2026

  return {
    name: family.name,
    slug: family.slug,
    base,
    semantic,
    family,
    ui: {
      accent: family.accent,
      accentBright: family.accentBright,
      accentSoft: family.accentSoft,
      companion: family.companion,
      companionBright: family.companionBright,
      companionSoft: family.companionSoft,
      highlight: {
        base: semantic.auraGreen,
        bright: family.companionBright,
        hover: family.companionSoft,
      },
      focusBorder: withAlpha(family.accent, 'B3'),
      selection: withAlpha(family.accentSoft, 'DD'),
      selectionSoft: withAlpha(family.accentSoft, '60'),
      selectionStrong: withAlpha(family.accentSoft, '90'),
      selectionSolid: family.accentSoft,
      listSelection: withAlpha(family.accentSoft, '2E'),
      listSelectionFocus: withAlpha(family.accentSoft, '44'),
      warning: semantic.yellowBright,
      modified: family.accentBright,
      actionHover: semantic.auraGreen,
      lineHighlight: base.surfaceAlt,
      link: family.accent,
      linkHover: family.accentBright,
      button: family.accentSoft,
      buttonHover: family.accent,
      successSurface: withAlpha(semantic.green, '1F'),
      warningSurface: withAlpha(semantic.yellow, '24'),
      errorSurface: withAlpha(semantic.red, '24'),
      infoSurface: withAlpha(family.accent, '1F'),
      subtleAccentSurface: withAlpha(family.accentSoft, '1A'),
      mediumAccentSurface: withAlpha(family.accentSoft, '26'),
      strongAccentSurface: withAlpha(family.accentSoft, '4D'),
      foregroundOverlayLow: withAlpha(base.surfaceHover, 'CC'),
      foregroundOverlayHigh: withAlpha(base.borderStrong, '99'),
      scrollbar: withAlpha(base.foregroundSubtle, '33'),
      scrollbarHover: withAlpha(base.foregroundSubtle, '66'),
      scrollbarActive: withAlpha(base.foregroundSubtle, '99'),
      debugBackground: '#A19C77',
      breakpointBackground: '#353424',
    },
    ansi: {
      black: base.appBackground,
      red: semantic.red,
      green: semantic.green,
      yellow: semantic.yellow,
      blue: family.accent,
      magenta: family.companion,
      cyan: family.accent,
      white: base.foreground,
      brightBlack: base.foregroundSubtle,
      brightRed: semantic.redBright,
      brightGreen: semantic.auraGreen,
      brightYellow: semantic.yellowBright,
      brightBlue: family.accentBright,
      brightMagenta: family.companionBright,
      brightCyan: family.accentBright,
      brightWhite: base.foregroundStrong,
      dimBlack: base.disabled,
      dimRed: semantic.red,
      dimGreen: semantic.green,
      dimYellow: semantic.orange,
      dimBlue: family.accentSoft,
      dimMagenta: family.companionSoft,
      dimCyan: family.accentSoft,
      dimWhite: base.foregroundMuted,
    },
    syntax: {
      attribute: family.accent,
      boolean: family.accent,
      class: family.accent,
      comment: base.comment,
      commentDoc: base.foregroundMuted,
      constant: family.accent,
      constructor: family.accent,
      decorator: family.accent,
      embedded: base.foreground,
      enum: family.accent,
      enumMember: family.accent,
      function: family.accentBright,
      functionSpecial: semantic.orangeBright,
      keyword: family.accentBright,
      label: family.companionBright,
      link: family.accent,
      macro: family.accent,
      namespace: semantic.infoBright,
      number: semantic.orange,
      operator: family.accentBright,
      parameter: family.companionBright,
      property: family.accent,
      punctuation: base.foreground,
      punctuationMuted: base.foregroundMuted,
      regexp: semantic.yellowBright,
      selector: semantic.auraGreen,
      string: semantic.auraGreen,
      stringEscape: semantic.yellowBright,
      stringSpecial: semantic.yellowBright,
      tag: semantic.auraGreen,
      title: family.accentBright,
      type: family.accent,
      variable: base.foreground,
      variableSpecial: family.accent,
    },
  }
}
