# {{ name }}

background = {{ accent12 }}
foreground = {{ accent7 }}
cursor-color = {{ uiAccentBright }}
selection-background = {{ uiSelectionSolid }}
selection-foreground = {{ accent7 }}

palette = 0={{ ansiBlack }}
palette = 1={{ ansiRed }}
palette = 2={{ ansiGreen }}
palette = 3={{ ansiYellow }}
palette = 4={{ ansiBlue }}
palette = 5={{ ansiMagenta }}
palette = 6={{ ansiCyan }}
palette = 7={{ ansiWhite }}
palette = 8={{ ansiBrightBlack }}
palette = 9={{ ansiBrightRed }}
palette = 10={{ ansiBrightGreen }}
palette = 11={{ ansiBrightYellow }}
palette = 12={{ ansiBrightBlue }}
palette = 13={{ ansiBrightMagenta }}
palette = 14={{ ansiBrightCyan }}
palette = 15={{ ansiBrightWhite }}
