id = "{{ slug }}"
name = "{{ displayName }}"
schema_version = 1
version = "{{ version }}"
authors = ["{{ author.name }} <{{ author.email }}>"]
description = "A forked 2026 adaptation of Aura Theme for {{ portName }}"
repository = "{{{ repository }}}"
